# Default HSDT architecture parameters. Combine with config/base.yaml (loaded by default).
model:
  model_name: hsdt
  model_kwargs:
    in_channels: 1
    channels: 16
    num_half_layer: 5
    downsample_layers:
      - 1
      - 3
    num_bands: 81
