# Default SSRT architecture parameters. Combine with config/base.yaml (loaded by default).
model:
  model_name: ssrt
  model_kwargs:
    upscale: 1
    img_size:
      - 64
      - 64
    window_size: 8
    img_range: 1.0
    depths:
      - 2
      - 2
      - 6
      - 2
      - 2
    embed_dim: 16
    num_heads:
      - 2
      - 2
      - 2
      - 2
      - 2
    mlp_ratio: 2
    upsampler: null
    in_chans: 1
    gate: sru
    if_mlp_s: true
