# Common training defaults shared across runs. Override selectively via additional config files.
seed_everything: true

model:
  lr: 3e-4
  save_test: false

data:
  base_dir: "data"
  spatial_factor: 64
  out_bands: 81
  preprocess_data: false
  gaussian_noises:
    - 30
  train_files:
    - Pavia.mat
    - Forest.mat
    - cuprite512.mat
  test_files:
    - KSC.mat
  patch_test: false
  batch_size: 1
  num_workers: 0

trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: "bf16-mixed"
  callbacks:
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: 'epoch'
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: "val_ssim"
        mode: "max"
        save_top_k: 1
        dirpath: "checkpoints/best/"
        filename: "epoch_{epoch}-ssim_{val_ssim:.4f}"
        save_last: false
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: "val_psnr"
        mode: "max"
        save_top_k: 1
        dirpath: "checkpoints/best/"
        filename: "epoch_{epoch}-psnr_{val_psnr:.2f}"
        save_last: false
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        every_n_epochs: 5
        save_top_k: -1
        dirpath: "checkpoints/interval/"
        filename: "epoch-{epoch}"
        save_last: false
  fast_dev_run: false
  max_epochs: 80
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: null
  check_val_every_n_epoch: 1
  num_sanity_val_steps: null
  log_every_n_steps: 10
  enable_checkpointing: true
  enable_progress_bar: true
  enable_model_summary: true
  accumulate_grad_batches: 1
  logger:
    class_path: lightning.pytorch.loggers.TensorBoardLogger
    init_args:
      save_dir: logs/
      name: hsdt_lightning
  gradient_clip_val: 1.0
  gradient_clip_algorithm: "norm"
  deterministic: null
  benchmark: null
  inference_mode: true
  use_distributed_sampler: true
  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: null
  model_registry: null

ckpt_path: null
