# Overfit a single batch / quick smoke test. Combine with config/base.yaml and a model config.
model:
  lr: 1e-3
  save_test: true

data:
  patch_test: false
  batch_size: 8

trainer:
  max_epochs: -1
  max_steps: 5000
