# Local version of train.yaml that use batch size of 2
# lightning.pytorch==2.5.2
seed_everything: true

# Tuner Settings
# run_lr_finder: True
# show_lr_plot: True
# run_batch_size_finder: True
# batch_size_finder_mode: "power"

model:
  in_channels: 1
  channels: 16
  encoder_count: 5
  downsample_layers:
  - 1
  - 3
  num_bands: 81   # No. of spectral bands
  lr: 3e-4        # TODO: Replace this with the value you get from lr finder
  save_test: false

data:
  base_dir: "data"
  spatial_factor: 64
  out_bands: 81
  preprocess_data: false
  gaussian_noises:
  - 30
  # - 50
  # - 70
  train_files: 
    - Pavia.mat
  test_files:
    - Pavia.mat
  patch_test: true
  batch_size: 2    # TODO: Replace this with the value you get from batch size finder
  num_workers: 0

trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  
  callbacks:
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: 'epoch'

    # Save best model based on SSIM
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: "val_ssim"
        mode: "max"
        save_top_k: 1
        dirpath: "checkpoints/best/"
        filename: "epoch_{epoch}-ssim_{val_ssim:.4f}"
        save_last: false

    # Save best model based on PSNR
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: "val_psnr"
        mode: "max"
        save_top_k: 1
        dirpath: "checkpoints/best/"
        filename: "epoch_{epoch}-psnr_{val_psnr:.2f}"
        save_last: false

    # Save every 5 epochs (regardless of score)
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        every_n_epochs: 5
        save_top_k: -1
        dirpath: "checkpoints/interval/"
        filename: "epoch-{epoch}"
        save_last: false
  fast_dev_run: false

  max_epochs: 80
  min_epochs: null
  max_steps: -1
  min_steps: null

  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: null
  check_val_every_n_epoch: 1
  num_sanity_val_steps: null

  # Log every 10 steps
  log_every_n_steps: 10

  enable_checkpointing: true
  enable_progress_bar: true
  enable_model_summary: true
  accumulate_grad_batches: 1
  logger:
    class_path: lightning.pytorch.loggers.TensorBoardLogger
    init_args:
      save_dir: logs/
      name: hsdt_lightning

  # Gradiant clipping to help stabilize training
  gradient_clip_val: 1.0
  gradient_clip_algorithm: "norm"

  deterministic: null
  benchmark: null
  inference_mode: true
  use_distributed_sampler: true

  # Profiler 
  # profiler:
  #   class_path: lightning.pytorch.profilers.AdvancedProfiler
  #   init_args:
  #     dirpath: "logs"
  #     filename: "profiler.txt"

  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: checkpoints
  model_registry: null
ckpt_path: null
